name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    # No branch restrictions for pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/challenge_app/requirements.txt

    - name: Set up GCP Service Account Key
      env:
        SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: echo "$SA_KEY" > sa_key.json

    - name: Authenticate with GCP
      run: gcloud auth activate-service-account --key-file=sa_key.json

    - name: Run tests
      run: |
        python -m pytest

